name: Docker Image CI

on:
  pull_request:
    types:
      - closed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag virtualTableTop:$(date +%s)
